### PR TITLE
Add assemblies strong-names

### LINKED ISSUE #47: Assembly is not strong-named
**Repro steps:**

1. Download the latest version from NuGet
2. Unpack the `.nupkg` file
3. Run `sn -vf DistributedLock.1.5.0\lib\net45\DistributedLock.dll`

**Expected:**
The `sn.exe` tool would output 

```
Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'DistributedLock.1.5.0\lib\net45\DistributedLock.dll' is valid
```

**Actual:**
The `sn.exe` tool outputs

```
Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

DistributedLock.1.5.0\lib\net45\DistributedLock.dll does not represent a strongly named assembly
```

**Observation:**
This blocks strong-named .NET assemblies from depending on `DistributedLock`. See [Why strong-name your assemblies?](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies)

### PR DESCRIPTION
**Pull request by pedropaulovc**
Add assemblies strong-names with a new .snk file generated. Fixes #47

### CODE REVIEW

**Comment by madelson** [comment]
Hi @pedropaulovc thanks for contributing.

Since adding a strong name to an assembly is a binary breaking change, I won't be able to merge this into the 1.x series.

I am currently working on the 2.0 version (see the 2.0 branch) which is intended to have strong-named assemblies. Would you consider performing this change on the 2.0 branch and filing a PR against that branch?

Thanks!

**Comment by pedropaulovc** [comment]
@madelson Sure. I addressed your comment in the latest iteration of the PR. Let me know if you'd like any other changes. Thanks!

**Comment by madelson** [comment]
Thanks! I’ll hopefully get a chance to look at this in the next couple of days.

Would a prerelease version be useful to you if it were made available?

**Comment by pedropaulovc** [comment]
I appreciate the offer but my team is pretty conservative in uptaking major version changes. We'll keep an eye for v2 release candidates. Thanks!

**Comment by madelson** [comment]
> We'll keep an eye for v2 release candidates.

Just for clarification, does this mean you'd be comfortable with something tagged as -rc, just not as -alpha?

**Pull request merged**
