### PR TITLE
tests: use testcontainers.postgres for integration tests

### PR DESCRIPTION
**Pull request by Meir017**

### CODE REVIEW

**Comment by Meir017** [comment]
same faileures as #208

**Comment by Meir017** [comment]
now after a couple tests compelete, all of the tests start to fail with the error `Unhandled exception. Npgsql.PostgresException (0x80004005): 53300: sorry, too many clients already`

**Comment by Meir017** [comment]
continued in #211

**Comment by madelson** [comment]
Do we need to configure Postgres to allow more connections? In the local setup docs for distributedlock believe there’s something about that.

**Comment by Meir017** [comment]
@madelson I had some issues modifying the configuration of the docker, so for PostgreSQL there are multiple containers starting and stopping, continued in #212

**Pull request closed without merging**
