### PR TITLE
.NETStandard 2.1 and .NET 4.7.2 migration - switching over to new Sql…

### PR DESCRIPTION
**Pull request by alesebi91**
Hi,
I've made the following changes to meet my needs on a project developed with .NetCore 3.1:
1. projects migration to .NETStandard 2.1 and .NET 4.7.2
2. Switched over to new SqlClient package (related to issue: https://github.com/madelson/DistributedLock/issues/25#issue-445421722)

### CODE REVIEW

**Comment by alesebi91** [comment]
Hi @madelson ,
I answer you by points:
1. I need it because I am migrating my project to Asp.Net Core 3.1 in order to run it into docker linux container. The old SqlClient are windows platform dependent and will no more mantained by Microsoft.
2. I haven't tried it. I migrated to the new package without codebase modification. 
3. New and old SqlClient share the same namespaces so they cannot be used side by side
4. I migrated them to align the library with the latest frameworks versions and because the new Microsoft.Data.SqlClient supports .NetFramework 4.6+, netstandard 2+ and netcore 2.1+. If you want I can also add compatibility to netstandard 2 and .NetFramework 4.6

Let me know if you need further implementations.

Thanks and enjoy the weekend!

**Comment by madelson** [comment]
Thanks @alesebi91 that context is helpful. In particular I wasn't aware that System.Data.SqlClient did not work at all on Linux.

I'm working on a new version of the library now that will incorporate this client as the default for .NET Standard 2.0 and newer (until I release a major version bump I plan to retain compatibility with the older frameworks). If I publish a prerelease version of this to NuGet.org in the next few days, would you be able to test it in your environment?

**Comment by alesebi91** [comment]
Thanks @madelson, It sonds good!
Let me know when prerelease will be available so I can test it in my environment

**Comment by madelson** [comment]
Prerelease is up on Nuget.org here: https://www.nuget.org/packages/DistributedLock/1.5.0-beta01

Let me know how it goes!

**Comment by alesebi91** [comment]
@madelson I just ran some tests with the new prerelease package and found no problems.

Thank you!

**Comment by madelson** [comment]
Thanks @alesebi91 I appreciate it. I've now released official v1.5 on NuGet. I'm going to close this PR since I found it simpler in this case to copy pieces over (due to maintaining the old frameworks). Thanks again for your help with this.

**Pull request closed without merging**
